name: "🐛 Bug Report"
description: Report a bug
title: "[BUG]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: e.g., The app crashes when I click on Save
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: The file should save without crashing
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: If applicable, add logs to help explain your problem.
      render: shell
      placeholder: |
        Paste logs here (use triple backticks for formatting)
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
      placeholder: e.g., Happens only on Windows 11
    validations:
      required: false
